name: create zip file

on: 
  push:
    branches:    
      - main
  pull_request:

jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: remove files
        run: rm -rf .github && rm -rf renovate.json
      - name: create zip
        run: zip -r namagomi-ResourcePack *
      - name: send  zip
        uses: actions/upload-artifact@v3
        with:
          name: zip_file
          path: namagomi-ResourcePack.zip